CREATE TABLE "students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "class_number" varchar(10)
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_name" varchar(255)
);

CREATE TABLE "feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" INT NOT NULL,
  "course_id" INT NOT NULL,
  "teacher_rating" INT CHECK (teacher_rating >= 1 AND teacher_rating <= 5),
  "job_rating" INT CHECK (job_rating >= 1 AND job_rating <= 5),
  "interest_rating" INT CHECK (interest_rating >= 1 AND interest_rating <= 5),
  "difficulty_rating" INT CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  "usefulness_rating" INT CHECK (usefulness_rating >= 1 AND usefulness_rating <= 5),
  "comment" TEXT,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "feedback" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");
ALTER TABLE "feedback" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

