CREATE TABLE "students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "class_number" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_name" varchar(255)
);

CREATE TABLE "feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "course_id" int,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

ALTER TABLE "feedback" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "feedback" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
